# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
  (?x)^(
    ml_viz/_version.py|
  )$

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: no-commit-to-branch
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-ast
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-xml
  - id: check-yaml
    exclude: '^(conda-recipe/meta.yaml)$'
  - id: debug-statements

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.3
  hooks:
  - id: ruff  # run the linter
    args: [ --fix, --select, I ]  # --select I sorts imports
  - id: ruff-format  # run the formatter

